config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: :json} do
    resources :incentives
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get :redeem, to: 'candidates#show'
  get :setup, to: 'researchers#show'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/incentive.rb
class Incentive < ApplicationRecord
end

app/controllers/api/incentives_controller.rb
class Api::IncentivesController < ApplicationController

  def index
    @incentives = Incentive.all
    
    render json: @incentives.to_json
  end

  def update
    @incentive = Incentive.find(params[:id])

    @incentive.update!(update_params)
    render json: @incentive.to_json
  end

  private

  def update_params
    params.require(:incentive).permit(:code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  def show
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/researchers_controller.rb
class ResearchersController < ApplicationController

  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incentives_helper.rb
module IncentivesHelper
end

app/views/candidates/show.html.erb
<div id="CandidateApp">

app/views/home/index.html.erb
<h1> GQ Coding Exercise: Incentive Redeemer </h1>
<div>
<%= link_to 'Setup', setup_path %>
</div>
<div>
<%= link_to 'Redeem', redeem_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GqTakeHome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/researchers/show.html.erb
<div id="ResearcherApp">